language: objective-c
osx_image: xcode8

# Important to specify the simulator SDK, otherwise Travis CI will attempt to
# build for the real iPhone and fail due to code-signing issues.
# See https://docs.travis-ci.com/user/languages/objective-c for details.
xcode_sdk: iphonesimulator10.0

before_install:
  - brew uninstall xctool
  - brew update
  - brew install xctool

xcode_project: NetworkReachability.xcodeproj
xcode_scheme: NetworkReachability
